-- RESET COMPLETO DEL SISTEMA DE LIBRERIA / INVENTARIO
-- ADVERTENCIA: este script elimina los datos de las tablas del sistema.
-- No elimina usuarios de Supabase Auth ni toca el esquema auth.

begin;

create extension if not exists pgcrypto;

drop function if exists public.registrar_movimiento(uuid, text, integer, text);
drop function if exists public.registrar_movimiento(bigint, text, integer, text);
drop function if exists public.registrar_venta(uuid, jsonb, numeric);
drop function if exists public.registrar_venta(bigint, jsonb, numeric);
drop function if exists public.registrar_compra(uuid, jsonb);
drop function if exists public.registrar_compra(bigint, jsonb);
drop function if exists public.set_updated_at();

drop table if exists public.detalle_compras cascade;
drop table if exists public.compras cascade;
drop table if exists public.detalle_ventas cascade;
drop table if exists public.ventas cascade;
drop table if exists public.movimientos_inventario cascade;
drop table if exists public.auditoria cascade;
drop table if exists public.productos cascade;
drop table if exists public.proveedores cascade;
drop table if exists public.clientes cascade;
drop table if exists public.usuarios cascade;
drop table if exists public.roles cascade;
drop table if exists public.categorias cascade;

create table public.roles (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz not null default now()
);

create table public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  email text not null unique,
  rol_id bigint references public.roles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz not null default now()
);

create table public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  correo text,
  direccion text,
  created_at timestamptz not null default now()
);

create table public.proveedores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  ruc text,
  telefono text,
  correo text,
  direccion text,
  created_at timestamptz not null default now()
);

create table public.productos (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  categoria_id bigint references public.categorias(id) on delete set null,
  proveedor_id bigint references public.proveedores(id) on delete set null,
  isbn text,
  autor text,
  editorial text,
  edicion text,
  anio_publicacion integer,
  numero_paginas integer,
  codigo_barras text,
  ubicacion_estante text,
  marca text,
  modelo text,
  unidad_medida text,
  precio_costo numeric(12, 2) not null default 0 check (precio_costo >= 0),
  precio_venta numeric(12, 2) not null check (precio_venta > 0),
  stock_actual integer not null default 0 check (stock_actual >= 0),
  stock_minimo integer not null default 0 check (stock_minimo >= 0),
  imagen_url text,
  descripcion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.movimientos_inventario (
  id uuid primary key default gen_random_uuid(),
  producto_id bigint not null references public.productos(id) on delete cascade,
  tipo text not null check (tipo in ('entrada', 'salida')),
  cantidad integer not null check (cantidad > 0),
  motivo text,
  usuario_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.ventas (
  id bigint generated by default as identity primary key,
  fecha timestamptz not null default now(),
  usuario_id uuid references auth.users(id) on delete set null,
  cliente_id bigint references public.clientes(id) on delete set null,
  subtotal numeric(12, 2) not null default 0 check (subtotal >= 0),
  impuesto numeric(12, 2) not null default 0 check (impuesto >= 0),
  total numeric(12, 2) not null default 0 check (total >= 0)
);

create table public.detalle_ventas (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.ventas(id) on delete cascade,
  producto_id bigint not null references public.productos(id),
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12, 2) not null check (precio_unitario >= 0),
  subtotal numeric(12, 2) not null check (subtotal >= 0)
);

create table public.compras (
  id bigint generated by default as identity primary key,
  proveedor_id bigint references public.proveedores(id) on delete set null,
  fecha timestamptz not null default now(),
  total numeric(12, 2) not null default 0 check (total >= 0)
);

create table public.detalle_compras (
  id bigint generated by default as identity primary key,
  compra_id bigint not null references public.compras(id) on delete cascade,
  producto_id bigint not null references public.productos(id),
  cantidad integer not null check (cantidad > 0),
  costo_unitario numeric(12, 2) not null check (costo_unitario >= 0)
);

create table public.auditoria (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid references auth.users(id) on delete set null,
  accion text not null,
  tabla text not null,
  registro_id text,
  fecha timestamptz not null default now(),
  descripcion text
);

insert into public.roles (nombre)
values ('administrador'), ('cajero'), ('almacen'), ('supervisor');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger productos_set_updated_at
before update on public.productos
for each row
execute function public.set_updated_at();

create index productos_categoria_id_idx on public.productos(categoria_id);
create index productos_proveedor_id_idx on public.productos(proveedor_id);
create index productos_nombre_idx on public.productos(nombre);
create index productos_codigo_idx on public.productos(codigo);
create index productos_isbn_idx on public.productos(isbn);
create index productos_autor_idx on public.productos(autor);
create index productos_editorial_idx on public.productos(editorial);
create index movimientos_producto_id_idx on public.movimientos_inventario(producto_id);
create index movimientos_created_at_idx on public.movimientos_inventario(created_at desc);
create index ventas_fecha_idx on public.ventas(fecha desc);
create index compras_fecha_idx on public.compras(fecha desc);
create index auditoria_fecha_idx on public.auditoria(fecha desc);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.roles to authenticated;
grant select, insert, update, delete on public.usuarios to authenticated;
grant select, insert, update, delete on public.categorias to authenticated;
grant select, insert, update, delete on public.clientes to authenticated;
grant select, insert, update, delete on public.proveedores to authenticated;
grant select, insert, update, delete on public.productos to authenticated;
grant select, insert on public.movimientos_inventario to authenticated;
grant select, insert, update, delete on public.ventas to authenticated;
grant select, insert, update, delete on public.detalle_ventas to authenticated;
grant select, insert, update, delete on public.compras to authenticated;
grant select, insert, update, delete on public.detalle_compras to authenticated;
grant select, insert on public.auditoria to authenticated;

alter table public.roles enable row level security;
alter table public.usuarios enable row level security;
alter table public.categorias enable row level security;
alter table public.clientes enable row level security;
alter table public.proveedores enable row level security;
alter table public.productos enable row level security;
alter table public.movimientos_inventario enable row level security;
alter table public.ventas enable row level security;
alter table public.detalle_ventas enable row level security;
alter table public.compras enable row level security;
alter table public.detalle_compras enable row level security;
alter table public.auditoria enable row level security;

create policy "Usuarios autenticados pueden leer roles"
on public.roles for select to authenticated using (true);

create policy "Usuarios autenticados pueden leer usuarios"
on public.usuarios for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear su usuario"
on public.usuarios for insert to authenticated
with check (id = (select auth.uid()));

create policy "Usuarios autenticados pueden actualizar su usuario"
on public.usuarios for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy "Usuarios autenticados pueden leer categorias"
on public.categorias for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear categorias"
on public.categorias for insert to authenticated with check (true);

create policy "Usuarios autenticados pueden actualizar categorias"
on public.categorias for update to authenticated using (true) with check (true);

create policy "Usuarios autenticados pueden eliminar categorias"
on public.categorias for delete to authenticated using (true);

create policy "Usuarios autenticados pueden leer clientes"
on public.clientes for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear clientes"
on public.clientes for insert to authenticated with check (true);

create policy "Usuarios autenticados pueden actualizar clientes"
on public.clientes for update to authenticated using (true) with check (true);

create policy "Usuarios autenticados pueden eliminar clientes"
on public.clientes for delete to authenticated using (true);

create policy "Usuarios autenticados pueden leer proveedores"
on public.proveedores for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear proveedores"
on public.proveedores for insert to authenticated with check (true);

create policy "Usuarios autenticados pueden actualizar proveedores"
on public.proveedores for update to authenticated using (true) with check (true);

create policy "Usuarios autenticados pueden eliminar proveedores"
on public.proveedores for delete to authenticated using (true);

create policy "Usuarios autenticados pueden leer productos"
on public.productos for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear productos"
on public.productos for insert to authenticated with check (true);

create policy "Usuarios autenticados pueden actualizar productos"
on public.productos for update to authenticated using (true) with check (true);

create policy "Usuarios autenticados pueden eliminar productos"
on public.productos for delete to authenticated using (true);

create policy "Usuarios autenticados pueden leer movimientos"
on public.movimientos_inventario for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear movimientos propios"
on public.movimientos_inventario for insert to authenticated
with check (usuario_id = (select auth.uid()));

create policy "Usuarios autenticados pueden leer ventas"
on public.ventas for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear ventas"
on public.ventas for insert to authenticated
with check (usuario_id = (select auth.uid()));

create policy "Usuarios autenticados pueden actualizar ventas"
on public.ventas for update to authenticated using (true) with check (true);

create policy "Usuarios autenticados pueden eliminar ventas"
on public.ventas for delete to authenticated using (true);

create policy "Usuarios autenticados pueden leer detalle ventas"
on public.detalle_ventas for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear detalle ventas"
on public.detalle_ventas for insert to authenticated with check (true);

create policy "Usuarios autenticados pueden actualizar detalle ventas"
on public.detalle_ventas for update to authenticated using (true) with check (true);

create policy "Usuarios autenticados pueden eliminar detalle ventas"
on public.detalle_ventas for delete to authenticated using (true);

create policy "Usuarios autenticados pueden leer compras"
on public.compras for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear compras"
on public.compras for insert to authenticated with check (true);

create policy "Usuarios autenticados pueden actualizar compras"
on public.compras for update to authenticated using (true) with check (true);

create policy "Usuarios autenticados pueden eliminar compras"
on public.compras for delete to authenticated using (true);

create policy "Usuarios autenticados pueden leer detalle compras"
on public.detalle_compras for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear detalle compras"
on public.detalle_compras for insert to authenticated with check (true);

create policy "Usuarios autenticados pueden actualizar detalle compras"
on public.detalle_compras for update to authenticated using (true) with check (true);

create policy "Usuarios autenticados pueden eliminar detalle compras"
on public.detalle_compras for delete to authenticated using (true);

create policy "Usuarios autenticados pueden leer auditoria"
on public.auditoria for select to authenticated using (true);

create policy "Usuarios autenticados pueden crear auditoria"
on public.auditoria for insert to authenticated
with check (usuario_id = (select auth.uid()));

create or replace function public.registrar_movimiento(
  p_producto_id bigint,
  p_tipo text,
  p_cantidad integer,
  p_motivo text default null
)
returns public.movimientos_inventario
language plpgsql
security invoker
as $$
declare
  v_stock_actual integer;
  v_stock_nuevo integer;
  v_movimiento public.movimientos_inventario;
begin
  if p_cantidad <= 0 then
    raise exception 'La cantidad debe ser mayor a 0.';
  end if;

  select stock_actual
    into v_stock_actual
  from public.productos
  where id = p_producto_id
  for update;

  if not found then
    raise exception 'Producto no encontrado.';
  end if;

  if p_tipo = 'entrada' then
    v_stock_nuevo := v_stock_actual + p_cantidad;
  elsif p_tipo = 'salida' then
    v_stock_nuevo := v_stock_actual - p_cantidad;
  else
    raise exception 'Tipo de movimiento invalido.';
  end if;

  if v_stock_nuevo < 0 then
    raise exception 'Stock insuficiente.';
  end if;

  update public.productos
  set stock_actual = v_stock_nuevo
  where id = p_producto_id;

  insert into public.movimientos_inventario (producto_id, tipo, cantidad, motivo, usuario_id)
  values (p_producto_id, p_tipo, p_cantidad, p_motivo, auth.uid())
  returning * into v_movimiento;

  insert into public.auditoria (usuario_id, accion, tabla, registro_id, descripcion)
  values (auth.uid(), 'crear', 'movimientos_inventario', v_movimiento.id::text, 'Movimiento de inventario registrado.');

  return v_movimiento;
end;
$$;

create or replace function public.registrar_venta(
  p_cliente_id bigint,
  p_items jsonb,
  p_impuesto numeric default 0
)
returns public.ventas
language plpgsql
security invoker
as $$
declare
  v_item jsonb;
  v_producto public.productos;
  v_cantidad integer;
  v_precio numeric(12, 2);
  v_subtotal numeric(12, 2) := 0;
  v_venta public.ventas;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta debe incluir productos.';
  end if;

  insert into public.ventas (usuario_id, cliente_id, subtotal, impuesto, total)
  values (auth.uid(), p_cliente_id, 0, coalesce(p_impuesto, 0), 0)
  returning * into v_venta;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_cantidad := (v_item ->> 'cantidad')::integer;

    if v_cantidad <= 0 then
      raise exception 'La cantidad vendida debe ser mayor a 0.';
    end if;

    select *
      into v_producto
    from public.productos
    where id = (v_item ->> 'producto_id')::bigint
    for update;

    if not found then
      raise exception 'Producto no encontrado.';
    end if;

    if v_producto.stock_actual < v_cantidad then
      raise exception 'Stock insuficiente para %.', v_producto.nombre;
    end if;

    v_precio := coalesce((v_item ->> 'precio_unitario')::numeric, v_producto.precio_venta);
    v_subtotal := v_subtotal + (v_cantidad * v_precio);

    insert into public.detalle_ventas (venta_id, producto_id, cantidad, precio_unitario, subtotal)
    values (v_venta.id, v_producto.id, v_cantidad, v_precio, v_cantidad * v_precio);

    update public.productos
    set stock_actual = stock_actual - v_cantidad
    where id = v_producto.id;

    insert into public.movimientos_inventario (producto_id, tipo, cantidad, motivo, usuario_id)
    values (v_producto.id, 'salida', v_cantidad, 'Venta', auth.uid());
  end loop;

  update public.ventas
  set subtotal = v_subtotal,
      impuesto = coalesce(p_impuesto, 0),
      total = v_subtotal + coalesce(p_impuesto, 0)
  where id = v_venta.id
  returning * into v_venta;

  insert into public.auditoria (usuario_id, accion, tabla, registro_id, descripcion)
  values (auth.uid(), 'crear', 'ventas', v_venta.id::text, 'Venta registrada.');

  return v_venta;
end;
$$;

create or replace function public.registrar_compra(
  p_proveedor_id bigint,
  p_items jsonb
)
returns public.compras
language plpgsql
security invoker
as $$
declare
  v_item jsonb;
  v_producto_id bigint;
  v_cantidad integer;
  v_costo numeric(12, 2);
  v_total numeric(12, 2) := 0;
  v_compra public.compras;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La compra debe incluir productos.';
  end if;

  insert into public.compras (proveedor_id, total)
  values (p_proveedor_id, 0)
  returning * into v_compra;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_producto_id := (v_item ->> 'producto_id')::bigint;
    v_cantidad := (v_item ->> 'cantidad')::integer;
    v_costo := (v_item ->> 'costo_unitario')::numeric;

    if v_cantidad <= 0 or v_costo < 0 then
      raise exception 'Detalle de compra invalido.';
    end if;

    insert into public.detalle_compras (compra_id, producto_id, cantidad, costo_unitario)
    values (v_compra.id, v_producto_id, v_cantidad, v_costo);

    update public.productos
    set stock_actual = stock_actual + v_cantidad,
        precio_costo = v_costo,
        proveedor_id = coalesce(p_proveedor_id, proveedor_id)
    where id = v_producto_id;

    if not found then
      raise exception 'Producto no encontrado.';
    end if;

    insert into public.movimientos_inventario (producto_id, tipo, cantidad, motivo, usuario_id)
    values (v_producto_id, 'entrada', v_cantidad, 'Compra', auth.uid());

    v_total := v_total + (v_cantidad * v_costo);
  end loop;

  update public.compras
  set total = v_total
  where id = v_compra.id
  returning * into v_compra;

  insert into public.auditoria (usuario_id, accion, tabla, registro_id, descripcion)
  values (auth.uid(), 'crear', 'compras', v_compra.id::text, 'Compra registrada.');

  return v_compra;
end;
$$;

revoke all on function public.registrar_movimiento(bigint, text, integer, text) from public;
revoke all on function public.registrar_venta(bigint, jsonb, numeric) from public;
revoke all on function public.registrar_compra(bigint, jsonb) from public;
grant execute on function public.registrar_movimiento(bigint, text, integer, text) to authenticated;
grant execute on function public.registrar_venta(bigint, jsonb, numeric) to authenticated;
grant execute on function public.registrar_compra(bigint, jsonb) to authenticated;

commit;

select
  'Base reiniciada correctamente' as estado,
  (select count(*) from public.roles) as roles_creados,
  (select count(*) from public.categorias) as categorias,
  (select count(*) from public.productos) as productos;
