create extension if not exists pgcrypto;

create table if not exists public.categorias (
  id uuid primary key default gen_random_uuid(),
  nombre text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  categoria_id uuid references public.categorias(id) on delete set null,
  precio_costo numeric(12, 2) not null default 0 check (precio_costo >= 0),
  precio_venta numeric(12, 2) not null check (precio_venta > 0),
  stock_actual integer not null default 0 check (stock_actual >= 0),
  stock_minimo integer not null default 0 check (stock_minimo >= 0),
  imagen_url text,
  descripcion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.movimientos_inventario (
  id uuid primary key default gen_random_uuid(),
  producto_id bigint not null references public.productos(id) on delete cascade,
  tipo text not null check (tipo in ('entrada', 'salida')),
  cantidad integer not null check (cantidad > 0),
  motivo text,
  usuario_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists productos_categoria_id_idx on public.productos(categoria_id);
create index if not exists productos_nombre_idx on public.productos(nombre);
create index if not exists movimientos_producto_id_idx on public.movimientos_inventario(producto_id);
create index if not exists movimientos_created_at_idx on public.movimientos_inventario(created_at desc);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.categorias to authenticated;
grant select, insert, update, delete on public.productos to authenticated;
grant select, insert on public.movimientos_inventario to authenticated;

alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.movimientos_inventario enable row level security;

drop policy if exists "Usuarios autenticados pueden leer categorias" on public.categorias;
drop policy if exists "Usuarios autenticados pueden crear categorias" on public.categorias;
drop policy if exists "Usuarios autenticados pueden actualizar categorias" on public.categorias;
drop policy if exists "Usuarios autenticados pueden eliminar categorias" on public.categorias;

create policy "Usuarios autenticados pueden leer categorias"
on public.categorias for select
to authenticated
using (true);

create policy "Usuarios autenticados pueden crear categorias"
on public.categorias for insert
to authenticated
with check (true);

create policy "Usuarios autenticados pueden actualizar categorias"
on public.categorias for update
to authenticated
using (true)
with check (true);

create policy "Usuarios autenticados pueden eliminar categorias"
on public.categorias for delete
to authenticated
using (true);

drop policy if exists "Usuarios autenticados pueden leer productos" on public.productos;
drop policy if exists "Usuarios autenticados pueden crear productos" on public.productos;
drop policy if exists "Usuarios autenticados pueden actualizar productos" on public.productos;
drop policy if exists "Usuarios autenticados pueden eliminar productos" on public.productos;

create policy "Usuarios autenticados pueden leer productos"
on public.productos for select
to authenticated
using (true);

create policy "Usuarios autenticados pueden crear productos"
on public.productos for insert
to authenticated
with check (true);

create policy "Usuarios autenticados pueden actualizar productos"
on public.productos for update
to authenticated
using (true)
with check (true);

create policy "Usuarios autenticados pueden eliminar productos"
on public.productos for delete
to authenticated
using (true);

drop policy if exists "Usuarios autenticados pueden leer movimientos" on public.movimientos_inventario;
drop policy if exists "Usuarios autenticados pueden crear movimientos propios" on public.movimientos_inventario;

create policy "Usuarios autenticados pueden leer movimientos"
on public.movimientos_inventario for select
to authenticated
using (true);

create policy "Usuarios autenticados pueden crear movimientos propios"
on public.movimientos_inventario for insert
to authenticated
with check (usuario_id = (select auth.uid()));

alter table public.productos add column if not exists isbn text;
alter table public.productos add column if not exists autor text;
alter table public.productos add column if not exists editorial text;
alter table public.productos add column if not exists edicion text;
alter table public.productos add column if not exists anio_publicacion integer;
alter table public.productos add column if not exists numero_paginas integer;
alter table public.productos add column if not exists codigo_barras text;
alter table public.productos add column if not exists ubicacion_estante text;
alter table public.productos add column if not exists proveedor_id uuid;
alter table public.productos add column if not exists marca text;
alter table public.productos add column if not exists modelo text;
alter table public.productos add column if not exists unidad_medida text;

create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  nombre text not null unique,
  created_at timestamptz not null default now()
);

insert into public.roles (nombre)
values ('administrador'), ('cajero'), ('almacen'), ('supervisor')
on conflict (nombre) do nothing;

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  email text not null unique,
  rol_id uuid references public.roles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  telefono text,
  correo text,
  direccion text,
  created_at timestamptz not null default now()
);

create table if not exists public.proveedores (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  ruc text,
  telefono text,
  correo text,
  direccion text,
  created_at timestamptz not null default now()
);

alter table public.productos
  drop constraint if exists productos_proveedor_id_fkey;

alter table public.productos
  add constraint productos_proveedor_id_fkey
  foreign key (proveedor_id) references public.proveedores(id) on delete set null;

create table if not exists public.ventas (
  id uuid primary key default gen_random_uuid(),
  fecha timestamptz not null default now(),
  usuario_id uuid references auth.users(id) on delete set null,
  cliente_id uuid references public.clientes(id) on delete set null,
  subtotal numeric(12, 2) not null default 0 check (subtotal >= 0),
  impuesto numeric(12, 2) not null default 0 check (impuesto >= 0),
  total numeric(12, 2) not null default 0 check (total >= 0)
);

create table if not exists public.detalle_ventas (
  id uuid primary key default gen_random_uuid(),
  venta_id uuid not null references public.ventas(id) on delete cascade,
  producto_id bigint not null references public.productos(id),
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12, 2) not null check (precio_unitario >= 0),
  subtotal numeric(12, 2) not null check (subtotal >= 0)
);

create table if not exists public.compras (
  id uuid primary key default gen_random_uuid(),
  proveedor_id uuid references public.proveedores(id) on delete set null,
  fecha timestamptz not null default now(),
  total numeric(12, 2) not null default 0 check (total >= 0)
);

create table if not exists public.detalle_compras (
  id uuid primary key default gen_random_uuid(),
  compra_id uuid not null references public.compras(id) on delete cascade,
  producto_id bigint not null references public.productos(id),
  cantidad integer not null check (cantidad > 0),
  costo_unitario numeric(12, 2) not null check (costo_unitario >= 0)
);

create table if not exists public.auditoria (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid references auth.users(id) on delete set null,
  accion text not null,
  tabla text not null,
  registro_id uuid,
  fecha timestamptz not null default now(),
  descripcion text
);

create index if not exists productos_isbn_idx on public.productos(isbn);
create index if not exists productos_autor_idx on public.productos(autor);
create index if not exists productos_editorial_idx on public.productos(editorial);
create index if not exists productos_proveedor_id_idx on public.productos(proveedor_id);
create index if not exists ventas_fecha_idx on public.ventas(fecha desc);
create index if not exists compras_fecha_idx on public.compras(fecha desc);
create index if not exists auditoria_fecha_idx on public.auditoria(fecha desc);

grant select, insert, update, delete on public.roles to authenticated;
grant select, insert, update, delete on public.usuarios to authenticated;
grant select, insert, update, delete on public.clientes to authenticated;
grant select, insert, update, delete on public.proveedores to authenticated;
grant select, insert, update, delete on public.ventas to authenticated;
grant select, insert, update, delete on public.detalle_ventas to authenticated;
grant select, insert, update, delete on public.compras to authenticated;
grant select, insert, update, delete on public.detalle_compras to authenticated;
grant select, insert on public.auditoria to authenticated;

alter table public.roles enable row level security;
alter table public.usuarios enable row level security;
alter table public.clientes enable row level security;
alter table public.proveedores enable row level security;
alter table public.ventas enable row level security;
alter table public.detalle_ventas enable row level security;
alter table public.compras enable row level security;
alter table public.detalle_compras enable row level security;
alter table public.auditoria enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'roles',
    'usuarios',
    'clientes',
    'proveedores',
    'ventas',
    'detalle_ventas',
    'compras',
    'detalle_compras',
    'auditoria'
  ]
  loop
    execute format('drop policy if exists "Usuarios autenticados pueden leer %s" on public.%I', table_name, table_name);
    execute format('create policy "Usuarios autenticados pueden leer %s" on public.%I for select to authenticated using (true)', table_name, table_name);
  end loop;
end $$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'roles',
    'usuarios',
    'clientes',
    'proveedores',
    'ventas',
    'detalle_ventas',
    'compras',
    'detalle_compras'
  ]
  loop
    execute format('drop policy if exists "Usuarios autenticados pueden crear %s" on public.%I', table_name, table_name);
    execute format('drop policy if exists "Usuarios autenticados pueden actualizar %s" on public.%I', table_name, table_name);
    execute format('drop policy if exists "Usuarios autenticados pueden eliminar %s" on public.%I', table_name, table_name);

    execute format('create policy "Usuarios autenticados pueden crear %s" on public.%I for insert to authenticated with check (true)', table_name, table_name);
    execute format('create policy "Usuarios autenticados pueden actualizar %s" on public.%I for update to authenticated using (true) with check (true)', table_name, table_name);
    execute format('create policy "Usuarios autenticados pueden eliminar %s" on public.%I for delete to authenticated using (true)', table_name, table_name);
  end loop;
end $$;

drop policy if exists "Usuarios autenticados pueden crear auditoria" on public.auditoria;

create policy "Usuarios autenticados pueden crear auditoria"
on public.auditoria for insert
to authenticated
with check (usuario_id = (select auth.uid()));

drop function if exists public.registrar_movimiento(uuid, text, integer, text);
drop function if exists public.registrar_movimiento(bigint, text, integer, text);
create or replace function public.registrar_movimiento(
  p_producto_id bigint,
  p_tipo text,
  p_cantidad integer,
  p_motivo text default null
)
returns public.movimientos_inventario
language plpgsql
security invoker
as $$
declare
  v_stock_actual integer;
  v_stock_nuevo integer;
  v_movimiento public.movimientos_inventario;
begin
  if p_cantidad <= 0 then
    raise exception 'La cantidad debe ser mayor a 0.';
  end if;

  select stock_actual
    into v_stock_actual
  from public.productos
  where id = p_producto_id
  for update;

  if not found then
    raise exception 'Producto no encontrado.';
  end if;

  if p_tipo = 'entrada' then
    v_stock_nuevo := v_stock_actual + p_cantidad;
  elsif p_tipo = 'salida' then
    v_stock_nuevo := v_stock_actual - p_cantidad;
  else
    raise exception 'Tipo de movimiento inválido.';
  end if;

  if v_stock_nuevo < 0 then
    raise exception 'Stock insuficiente.';
  end if;

  update public.productos
  set stock_actual = v_stock_nuevo,
      updated_at = now()
  where id = p_producto_id;

  insert into public.movimientos_inventario (producto_id, tipo, cantidad, motivo, usuario_id)
  values (p_producto_id, p_tipo, p_cantidad, p_motivo, auth.uid())
  returning * into v_movimiento;

  insert into public.auditoria (usuario_id, accion, tabla, registro_id, descripcion)
  values (auth.uid(), 'crear', 'movimientos_inventario', v_movimiento.id, 'Movimiento de inventario registrado.');

  return v_movimiento;
end;
$$;

grant execute on function public.registrar_movimiento(bigint, text, integer, text) to authenticated;

drop function if exists public.registrar_venta(uuid, jsonb, numeric);
create or replace function public.registrar_venta(
  p_cliente_id uuid,
  p_items jsonb,
  p_impuesto numeric default 0
)
returns public.ventas
language plpgsql
security invoker
as $$
declare
  v_item jsonb;
  v_producto public.productos;
  v_cantidad integer;
  v_precio numeric(12, 2);
  v_subtotal numeric(12, 2) := 0;
  v_venta public.ventas;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta debe incluir productos.';
  end if;

  insert into public.ventas (usuario_id, cliente_id, subtotal, impuesto, total)
  values (auth.uid(), p_cliente_id, 0, coalesce(p_impuesto, 0), 0)
  returning * into v_venta;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_cantidad := (v_item ->> 'cantidad')::integer;

    if v_cantidad <= 0 then
      raise exception 'La cantidad vendida debe ser mayor a 0.';
    end if;

    select *
      into v_producto
    from public.productos
    where id = (v_item ->> 'producto_id')::bigint
    for update;

    if not found then
      raise exception 'Producto no encontrado.';
    end if;

    if v_producto.stock_actual < v_cantidad then
      raise exception 'Stock insuficiente para %.', v_producto.nombre;
    end if;

    v_precio := coalesce((v_item ->> 'precio_unitario')::numeric, v_producto.precio_venta);
    v_subtotal := v_subtotal + (v_cantidad * v_precio);

    insert into public.detalle_ventas (venta_id, producto_id, cantidad, precio_unitario, subtotal)
    values (v_venta.id, v_producto.id, v_cantidad, v_precio, v_cantidad * v_precio);

    update public.productos
    set stock_actual = stock_actual - v_cantidad,
        updated_at = now()
    where id = v_producto.id;

    insert into public.movimientos_inventario (producto_id, tipo, cantidad, motivo, usuario_id)
    values (v_producto.id, 'salida', v_cantidad, 'Venta', auth.uid());
  end loop;

  update public.ventas
  set subtotal = v_subtotal,
      impuesto = coalesce(p_impuesto, 0),
      total = v_subtotal + coalesce(p_impuesto, 0)
  where id = v_venta.id
  returning * into v_venta;

  insert into public.auditoria (usuario_id, accion, tabla, registro_id, descripcion)
  values (auth.uid(), 'crear', 'ventas', v_venta.id, 'Venta registrada.');

  return v_venta;
end;
$$;

grant execute on function public.registrar_venta(uuid, jsonb, numeric) to authenticated;

drop function if exists public.registrar_compra(uuid, jsonb);
create or replace function public.registrar_compra(
  p_proveedor_id uuid,
  p_items jsonb
)
returns public.compras
language plpgsql
security invoker
as $$
declare
  v_item jsonb;
  v_producto_id bigint;
  v_cantidad integer;
  v_costo numeric(12, 2);
  v_total numeric(12, 2) := 0;
  v_compra public.compras;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La compra debe incluir productos.';
  end if;

  insert into public.compras (proveedor_id, total)
  values (p_proveedor_id, 0)
  returning * into v_compra;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_producto_id := (v_item ->> 'producto_id')::bigint;
    v_cantidad := (v_item ->> 'cantidad')::integer;
    v_costo := (v_item ->> 'costo_unitario')::numeric;

    if v_cantidad <= 0 or v_costo < 0 then
      raise exception 'Detalle de compra inválido.';
    end if;

    insert into public.detalle_compras (compra_id, producto_id, cantidad, costo_unitario)
    values (v_compra.id, v_producto_id, v_cantidad, v_costo);

    update public.productos
    set stock_actual = stock_actual + v_cantidad,
        precio_costo = v_costo,
        proveedor_id = coalesce(p_proveedor_id, proveedor_id),
        updated_at = now()
    where id = v_producto_id;

    if not found then
      raise exception 'Producto no encontrado.';
    end if;

    insert into public.movimientos_inventario (producto_id, tipo, cantidad, motivo, usuario_id)
    values (v_producto_id, 'entrada', v_cantidad, 'Compra', auth.uid());

    v_total := v_total + (v_cantidad * v_costo);
  end loop;

  update public.compras
  set total = v_total
  where id = v_compra.id
  returning * into v_compra;

  insert into public.auditoria (usuario_id, accion, tabla, registro_id, descripcion)
  values (auth.uid(), 'crear', 'compras', v_compra.id, 'Compra registrada.');

  return v_compra;
end;
$$;

grant execute on function public.registrar_compra(uuid, jsonb) to authenticated;
